feat: add workbox exercices
sfeir-open-source/sfeir-school-pwa pull request #72
Opened 2020-09-14 13:06 UTC by SetiZ

fixes #21

2020-09-17 08:12 UTC, geromegrignon reviewed
En plus du commentaire, quand je lance le script *workbox*, j'ai l'erreur suivante : 

```
(node:47434) UnhandledPromiseRejectionWarning: Error: Unable to find a place to inject the manifest. Please ensure that your service worker file contains the following: self.__WB_MANIFEST

```

2020-09-17 08:12 UTC, geromegrignon commented on package.json
> +    "workbox": "node steps/workbox-2/workbox-build.js"
changer `workbox-build.js` par `workbox-exercice.js`

2020-09-17 09:47 UTC, SetiZ commented on package.json
> +    "workbox": "node steps/workbox-2/workbox-build.js"
oups oui !

2020-09-17 09:48 UTC, SetiZ commented
> En plus du commentaire, quand je lance le script _workbox_, j'ai l'erreur suivante :
> 
> ```
> (node:47434) UnhandledPromiseRejectionWarning: Error: Unable to find a place to inject the manifest. Please ensure that your service worker file contains the following: self.__WB_MANIFEST
> ```

tu l'as lancé dans `workbox-2-solution` ?

2020-09-22 09:05 UTC, SetiZ commented
fixed!

2020-10-14 08:42 UTC, jefBinomed requested changes
2 /3 remarques mineures mais on pourra valider direct après

2020-10-14 08:42 UTC, jefBinomed commented on package.json
> +    "workbox": "node steps/workbox-2-solution/workbox-exercice.js"
pourquoi l'intérgrer en npm ? j'avoue que j'aurais plutôt gardé la ligne de commande indépendante de nos scripts npm.

2020-10-14 08:42 UTC, jefBinomed commented on steps/workbox-2/src/service-worker.js
> +importScripts('https://storage.googleapis.com/workbox-cdn/releases/4.3.1/workbox-sw.js');
tu voulais pas faire en sorte que les gens fassent un peu de config workbox ? car là, tu leur donne le fichier tout cuit :p

2022-09-02 09:56 UTC, closed without merging