FIX: fix speaker slide and change logo
sfeir-open-source/sfeir-school-pwa pull request #74
Opened 2020-10-02 15:50 UTC by SetiZ

- fix speaker slide
- change sfeir logo to white

2020-10-02 16:14 UTC, jefBinomed requested changes
Je vois pas l'intéret de rajouter le fichier sfeir blanc en svg si au final tu utilise le png :) ?

2020-10-02 16:14 UTC, jefBinomed commented on docs/web_modules/sfeir-school-theme/dist/js/sfeir-theme.js
> -    Reveal.addEventListener('ready', setTimeout(this._pageload.bind(this), 500));
C'est Prettier qui t'as fait ça ? car perso, je suis pas pour changer ça.

2020-10-02 16:17 UTC, SetiZ commented on docs/web_modules/sfeir-school-theme/dist/js/sfeir-theme.js
> -    Reveal.addEventListener('ready', setTimeout(this._pageload.bind(this), 500));
ça cassait cette page en fait : https://sfeir-open-source.github.io/sfeir-school-pwa/#/3. Je l'ai juste corrigé.

2020-10-05 09:47 UTC, jefBinomed approved these changes

2020-10-05 12:21 UTC, SetiZ commented on docs/web_modules/sfeir-school-theme/dist/js/sfeir-theme.js
> -    Reveal.addEventListener('ready', setTimeout(this._pageload.bind(this), 500));
je vais l'enlever et le corriger dans le theme plutot

2020-10-08 09:07 UTC, merged